server {
    listen 80;
    
    # Frontend files serve karne ke liye
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Backend api requests ko route karne ke liye
    location /api/ {
        proxy_pass http://backend-api:3000;
    }

    location /signup {
        proxy_pass http://backend-api:3000;
    }
}