version: '3.8'

services:
  # 🌐 Frontend (Nginx Jo Request Forward Karega)
  frontend-app:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend-api

  # 🟢 Backend Node App
  backend-api:
    build: ./backend
    container_name: backend_container
    ports:
      - "3000:3000"